= devops-stack-module-velero
// Document attributes to replace along the document
// Here you can define variables for something that keeps repeating along the text
:velero-chart-version: 5.0.2
:original-repo-url: https://github.com/vmware-tanzu/helm-charts

A https://devops-stack.io[DevOps Stack] module to deploy a backup solution based on https://velero.io[Velero].

This module add the ability to perform backups of a cluster. This includes all Kubernetes objects, although with the GitOps approach of the Devops Stack, it is not necessary to have a backup of all Kubernetes objects, as they are generally disposable and recreated by ArgoCD. 

The Velero chart used by this module is shipped in this repository as well, in order to avoid any unwanted behaviors caused by unsupported versions.

[cols="1,1,1",options="autowidth,header"]
|===
|Current Chart Version |Original Repository |Default Values
|*{velero-chart-version}* |{original-repo-url}/tree/main/charts/velero[Chart] | https://artifacthub.io/packages/helm/vmware-tanzu/velero/{velero-chart-version}?modal=values[`values.yaml`]
|===

== Usage

=== Backup

Here is an example of the module usage:

- A default backend in a AWS S3 bucket, accessed with a ServiceAccount
- A schedule at 4 a.m, which uses EBS snapshots as backend for PVC
- A schedule at 2 a.m, which uses Restic as backend for PVC
- Prometheus monitoring with a Grafana dashboard

[source,terraform]
----
module "backup" {
  source           = "git::https://github.com/camptocamp/devops-stack-module-velero.git//eks"
  cluster_name     = local.cluster_name
  base_domain      = local.base_domain
  argocd_namespace = module.argocd_bootstrap.argocd_namespace

  ``
  enable_monitoring_dashboard = true

  # Automated backups can be specified.
  #
  # The included Resources is very important: if the resource `pods` is specified,
  # then velero will not attempt to use the native snapshot feature of the object
  # storage of the cloud provider (EBS snapshots), and will use the File System Backup, i.e
  # Restic.
  backup_schedules = {

    # This schedule will use the native snapshot ability to backup the PVC
    snapshot-schedule = {
      # Can temporarly disable snapshot schedules
      disabled = false
      # Cron-style scheduling
      schedule = "2 4 * * *"
      template = {
        # Select the backend for this schedule
        storageLocation    = "backup-bucket"
        includedNamespaces = ["wordpress"]
        includedResources  = ["persistentVolumes", "persistentVolumeClaims"]
      }
    },
    # This schedule will force the Restic backend to backup the PVC
    restic-schedule = {
      disabled = false
      schedule = "2 2 * * *"
      template = {
        # If using an non-default location:
        storageLocation    = "backup-bucket"
        includedNamespaces = ["wordpress"]
        includedResources  = ["persistentVolumes", "persistentVolumeClaims", "pods"]
      }
    }
  }

  default_backup_storage = {
    bucket_id    = aws_s3_bucket.velero_backup_storage.id
    region       = aws_s3_bucket.velero_backup_storage.region
    iam_role_arn = module.iam_assumable_role_velero.iam_role_arn
  }

}

----

Once the Velero controller is deployed on the server, it is also possible to perform manual backup from the `velero` client:

[source,bash]
----
velero backup create \
    --included-namespaces wordpress,loki \
    --included-resources pv,pvc,pods \
    --storage-location my-s3-bucket \
    my-new-backup
----

=== Restore

The backup can be restored manually with the following commands:

[source,bash]
----
# Restore from a backup
velero restore create --from-backup my-new-backup
# Restore from the last backup of a schedule
velero restore create --from-schedule restic-schedule
----

TODO: Link to Velero CLI documentation

TODO: In order to perform restore successful

== Monitoring

TODO: grafana dashboard (screenshot), alerts

== Limitations

=== KinD setup

Velero cannot perform backups of `hostPath` volumes, which are the volumes used in a KinD setup. Therefore, this module cannot be used in a Devops stack on KinD.

== Technical Reference

=== Dependencies

==== `module.kube-prometheus-stack`

As this module contains a Prometheus metrics endpoint and a Grafana dashboard, it has to be deployed after the https://github.com/camptocamp/devops-stack-module-kube-prometheus-stack[Prometheus stack].

==== `module.argocd`

Velero is deployed as an ArgoCD application, which means that ArgoCD has to be deployed first.

==== S3 bucket or equivalent

In order to perform backups, Velero needs a storage location for backups, either a S3 compatible storage (AWS S3, Minio, etc.), Azure Blob storage, etc.

Velero backs all Kubernetes objects to the designated

// BEGIN_TF_DOCS
=== Requirements

The following requirements are needed by this module:

- [[requirement_argocd]] <<requirement_argocd,argocd>> (>= 4)

- [[requirement_kubernetes]] <<requirement_kubernetes,kubernetes>> (~> 2)

- [[requirement_null]] <<requirement_null,null>> (>= 3)

- [[requirement_utils]] <<requirement_utils,utils>> (>= 1)

=== Providers

The following providers are used by this module:

- [[provider_null]] <<provider_null,null>> (>= 3)

- [[provider_random]] <<provider_random,random>>

- [[provider_kubernetes]] <<provider_kubernetes,kubernetes>> (~> 2)

- [[provider_helm]] <<provider_helm,helm>>

- [[provider_utils]] <<provider_utils,utils>> (>= 1)

- [[provider_argocd]] <<provider_argocd,argocd>> (>= 4)

=== Resources

The following resources are used by this module:

- https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/application[argocd_application.this] (resource)
- https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/project[argocd_project.this] (resource)
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/namespace[kubernetes_namespace.velero_namespace] (resource)
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/secret[kubernetes_secret.velero_repo_credentials] (resource)
- https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource[null_resource.dependencies] (resource)
- https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource[null_resource.k8s_resources] (resource)
- https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource[null_resource.this] (resource)
- https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password[random_password.restic_repo_password] (resource)
- https://registry.terraform.io/providers/hashicorp/helm/latest/docs/data-sources/template[helm_template.this] (data source)
- https://registry.terraform.io/providers/cloudposse/utils/latest/docs/data-sources/deep_merge_yaml[utils_deep_merge_yaml.values] (data source)

=== Required Inputs

The following input variables are required:

==== [[input_cluster_name]] <<input_cluster_name,cluster_name>>

Description: Name given to the cluster. Value used for naming some the resources created by the module.

Type: `string`

==== [[input_base_domain]] <<input_base_domain,base_domain>>

Description: Base domain of the cluster. Value used for the ingress' URL of the application.

Type: `string`

=== Optional Inputs

The following input variables are optional (have default values):

==== [[input_argocd_namespace]] <<input_argocd_namespace,argocd_namespace>>

Description: Namespace used by Argo CD where the Application and AppProject resources should be created.

Type: `string`

Default: `"argocd"`

==== [[input_target_revision]] <<input_target_revision,target_revision>>

Description: Override of target revision of the application chart.

Type: `string`

Default: `"v1.0.0"`

==== [[input_cluster_issuer]] <<input_cluster_issuer,cluster_issuer>>

Description: SSL certificate issuer to use. Usually you would configure this value as `letsencrypt-staging` or `letsencrypt-prod` on your root `*.tf` files.

Type: `string`

Default: `"ca-issuer"`

==== [[input_namespace]] <<input_namespace,namespace>>

Description: Namespace where the applications's Kubernetes resources should be created. Namespace will be created in case it doesn't exist.

Type: `string`

Default: `"velero"`

==== [[input_helm_values]] <<input_helm_values,helm_values>>

Description: Helm chart value overrides. They should be passed as a list of HCL structures.

Type: `any`

Default: `[]`

==== [[input_app_autosync]] <<input_app_autosync,app_autosync>>

Description: Automated sync options for the Argo CD Application resource.

Type:
[source,hcl]
----
object({
    allow_empty = optional(bool)
    prune       = optional(bool)
    self_heal   = optional(bool)
  })
----

Default:
[source,json]
----
{
  "allow_empty": false,
  "prune": true,
  "self_heal": true
}
----

==== [[input_dependency_ids]] <<input_dependency_ids,dependency_ids>>

Description: IDs of the other modules on which this module depends on.

Type: `map(string)`

Default: `{}`

==== [[input_backup_schedules]] <<input_backup_schedules,backup_schedules>>

Description: TBD

Type:
[source,hcl]
----
map(object({
    disabled    = optional(bool, false)
    labels      = optional(map(string), {})
    annotations = optional(map(string), {})
    schedule    = string
    template = object({
      # labels             = optional(map(string), {}) # TODO: test
      # annotations        = optional(map(string), {}) # TODO: test
      storageLocation    = optional(string)
      ttl                = optional(string)
      includedNamespaces = list(string)
      includedResources  = list(string)
      # enableSnapshot     = optional(bool, true)
    })
  }))
----

Default: `null`

==== [[input_enable_monitoring_dashboard]] <<input_enable_monitoring_dashboard,enable_monitoring_dashboard>>

Description: Boolean to enable the provisioning of a Velero dashboard for Grafana.

Type: `bool`

Default: `true`

==== [[input_alert_backup_timeout]] <<input_alert_backup_timeout,alert_backup_timeout>>

Description: Timeout in seconds before triggering the last successful backup alert

Type: `number`

Default: `86400`

=== Outputs

The following outputs are exported:

==== [[output_id]] <<output_id,id>>

Description: ID to pass other modules in order to refer to this module as a dependency.

==== [[output_restic_repo_password]] <<output_restic_repo_password,restic_repo_password>>

Description: the password to access the restic repositories
// END_TF_DOCS

=== Reference in table format

.Show tables
[%collapsible]
====
// BEGIN_TF_TABLES
= Requirements

[cols="a,a",options="header,autowidth"]
|===
|Name |Version
|[[requirement_argocd]] <<requirement_argocd,argocd>> |>= 4
|[[requirement_kubernetes]] <<requirement_kubernetes,kubernetes>> |~> 2
|[[requirement_null]] <<requirement_null,null>> |>= 3
|[[requirement_utils]] <<requirement_utils,utils>> |>= 1
|===

= Providers

[cols="a,a",options="header,autowidth"]
|===
|Name |Version
|[[provider_random]] <<provider_random,random>> |n/a
|[[provider_kubernetes]] <<provider_kubernetes,kubernetes>> |~> 2
|[[provider_helm]] <<provider_helm,helm>> |n/a
|[[provider_utils]] <<provider_utils,utils>> |>= 1
|[[provider_argocd]] <<provider_argocd,argocd>> |>= 4
|[[provider_null]] <<provider_null,null>> |>= 3
|===

= Resources

[cols="a,a",options="header,autowidth"]
|===
|Name |Type
|https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/application[argocd_application.this] |resource
|https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/project[argocd_project.this] |resource
|https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/namespace[kubernetes_namespace.velero_namespace] |resource
|https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/secret[kubernetes_secret.velero_repo_credentials] |resource
|https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource[null_resource.dependencies] |resource
|https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource[null_resource.k8s_resources] |resource
|https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource[null_resource.this] |resource
|https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password[random_password.restic_repo_password] |resource
|https://registry.terraform.io/providers/hashicorp/helm/latest/docs/data-sources/template[helm_template.this] |data source
|https://registry.terraform.io/providers/cloudposse/utils/latest/docs/data-sources/deep_merge_yaml[utils_deep_merge_yaml.values] |data source
|===

= Inputs

[cols="a,a,a,a,a",options="header,autowidth"]
|===
|Name |Description |Type |Default |Required
|[[input_cluster_name]] <<input_cluster_name,cluster_name>>
|Name given to the cluster. Value used for naming some the resources created by the module.
|`string`
|n/a
|yes

|[[input_base_domain]] <<input_base_domain,base_domain>>
|Base domain of the cluster. Value used for the ingress' URL of the application.
|`string`
|n/a
|yes

|[[input_argocd_namespace]] <<input_argocd_namespace,argocd_namespace>>
|Namespace used by Argo CD where the Application and AppProject resources should be created.
|`string`
|`"argocd"`
|no

|[[input_target_revision]] <<input_target_revision,target_revision>>
|Override of target revision of the application chart.
|`string`
|`"v1.0.0"`
|no

|[[input_cluster_issuer]] <<input_cluster_issuer,cluster_issuer>>
|SSL certificate issuer to use. Usually you would configure this value as `letsencrypt-staging` or `letsencrypt-prod` on your root `*.tf` files.
|`string`
|`"ca-issuer"`
|no

|[[input_namespace]] <<input_namespace,namespace>>
|Namespace where the applications's Kubernetes resources should be created. Namespace will be created in case it doesn't exist.
|`string`
|`"velero"`
|no

|[[input_helm_values]] <<input_helm_values,helm_values>>
|Helm chart value overrides. They should be passed as a list of HCL structures.
|`any`
|`[]`
|no

|[[input_app_autosync]] <<input_app_autosync,app_autosync>>
|Automated sync options for the Argo CD Application resource.
|

[source]
----
object({
    allow_empty = optional(bool)
    prune       = optional(bool)
    self_heal   = optional(bool)
  })
----

|

[source]
----
{
  "allow_empty": false,
  "prune": true,
  "self_heal": true
}
----

|no

|[[input_dependency_ids]] <<input_dependency_ids,dependency_ids>>
|IDs of the other modules on which this module depends on.
|`map(string)`
|`{}`
|no

|[[input_backup_schedules]] <<input_backup_schedules,backup_schedules>>
|TBD
|

[source]
----
map(object({
    disabled    = optional(bool, false)
    labels      = optional(map(string), {})
    annotations = optional(map(string), {})
    schedule    = string
    template = object({
      # labels             = optional(map(string), {}) # TODO: test
      # annotations        = optional(map(string), {}) # TODO: test
      storageLocation    = optional(string)
      ttl                = optional(string)
      includedNamespaces = list(string)
      includedResources  = list(string)
      # enableSnapshot     = optional(bool, true)
    })
  }))
----

|`null`
|no

|[[input_enable_monitoring_dashboard]] <<input_enable_monitoring_dashboard,enable_monitoring_dashboard>>
|Boolean to enable the provisioning of a Velero dashboard for Grafana.
|`bool`
|`true`
|no

|[[input_alert_backup_timeout]] <<input_alert_backup_timeout,alert_backup_timeout>>
|Timeout in seconds before triggering the last successful backup alert
|`number`
|`86400`
|no

|===

= Outputs

[cols="a,a",options="header,autowidth"]
|===
|Name |Description
|[[output_id]] <<output_id,id>> |ID to pass other modules in order to refer to this module as a dependency.
|[[output_restic_repo_password]] <<output_restic_repo_password,restic_repo_password>> |the password to access the restic repositories
|===
// END_TF_TABLES
====
