= EKS variant

== Usage

=== Backup

Here is an example of the module usage:

- A default backend in a AWS S3 bucket, accessed with a ServiceAccount
- A schedule at 4 a.m, which uses EBS snapshots as backend for PVC
- A schedule at 2 a.m, which uses Restic as backend for PVC
- Prometheus monitoring with a Grafana dashboard

IMPORTANT: The `includedResources` variable is very important: if the resource `pods` is
specified, then velero will not attempt to use the native snapshot feature of
the object storage of the cloud provider (EBS snapshots), and will use the File
System Backup, i.e Restic.

[source,terraform]
----
module "velero" {
  source           = "git::https://github.com/camptocamp/devops-stack-module-velero.git//eks?ref=<RELEASE>"
  cluster_name     = local.cluster_name
  base_domain      = local.base_domain
  argocd_namespace = module.argocd_bootstrap.argocd_namespace

  enable_monitoring_dashboard = true

  # Automated backups can be specified.
  backup_schedules = {

    # This schedule will use the native snapshot ability to backup the PVC
    snapshot-schedule = {
      # Can temporarly disable snapshot schedules
      disabled = false
      # Cron-style scheduling
      schedule = "2 4 * * *"
      template = {
        # Select the backend for this schedule
        storageLocation    = "backup-bucket"
        includedNamespaces = ["wordpress"]
        includedResources  = ["persistentVolumes", "persistentVolumeClaims"]
      }
    },
    # This schedule will force the Restic backend to backup the PVC
    restic-schedule = {
      disabled = false
      schedule = "2 2 * * *"
      template = {
        # If using an non-default location:
        storageLocation    = "backup-bucket"
        includedNamespaces = ["wordpress"]
        includedResources  = ["persistentVolumes", "persistentVolumeClaims", "pods"]
      }
    }
  }

  default_backup_storage = {
    bucket_id    = aws_s3_bucket.velero_backup_storage.id
    region       = aws_s3_bucket.velero_backup_storage.region
    iam_role_arn = module.iam_assumable_role_velero.iam_role_arn
  }

  # Triggers an alert if too many backups are partially failed (ratio)
  alert_partially_failed_ratio = 0.25 # 25%
  # Triggers an alert if too many backups are failed (ratio)
  alert_failed_ratio = 0.1 # 10%
  # Triggers an alert if latest backup is older than this, in seconds
  alert_backup_timeout = 60 * 60 * 24

  dependency_ids = {
    argocd                = module.argocd_bootstrap.id
    kube-prometheus-stack = module.kube-prometheus-stack.id,
  }
}

----

== Technical Reference

=== Dependencies

==== `module.argocd_bootstrap.id`

Velero is deployed as an ArgoCD application, which means that ArgoCD has to be deployed first.

==== `module.kube-prometheus-stack.id`

As this module contains a Prometheus metrics endpoint and a Grafana dashboard, it has to be deployed after the https://github.com/camptocamp/devops-stack-module-kube-prometheus-stack[Prometheus stack].

// BEGIN_TF_DOCS
=== Requirements

The following requirements are needed by this module:

- [[requirement_argocd]] <<requirement_argocd,argocd>> (>= 4)

- [[requirement_kubernetes]] <<requirement_kubernetes,kubernetes>> (~> 2)

- [[requirement_null]] <<requirement_null,null>> (>= 3)

- [[requirement_utils]] <<requirement_utils,utils>> (>= 1)

=== Providers

The following providers are used by this module:

- [[provider_aws]] <<provider_aws,aws>>

=== Modules

The following Modules are called:

==== [[module_backup]] <<module_backup,backup>>

Source: ../

Version:

=== Resources

The following resources are used by this module:

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/region[aws_region.current] (data source)

=== Required Inputs

The following input variables are required:

==== [[input_default_backup_storage]] <<input_default_backup_storage,default_backup_storage>>

Description: AWS S3 bucket configuration values for the bucket where the backups will be stored.

Type:
[source,hcl]
----
object({
    bucket_id    = string
    region       = string
    iam_role_arn = string
  })
----

==== [[input_cluster_name]] <<input_cluster_name,cluster_name>>

Description: Name given to the cluster. Value used for naming some the resources created by the module.

Type: `string`

==== [[input_base_domain]] <<input_base_domain,base_domain>>

Description: Base domain of the cluster. Value used for the ingress' URL of the application.

Type: `string`

=== Optional Inputs

The following input variables are optional (have default values):

==== [[input_argocd_namespace]] <<input_argocd_namespace,argocd_namespace>>

Description: Namespace used by Argo CD where the Application and AppProject resources should be created.

Type: `string`

Default: `"argocd"`

==== [[input_target_revision]] <<input_target_revision,target_revision>>

Description: Override of target revision of the application chart.

Type: `string`

Default: `"v1.0.0"`

==== [[input_cluster_issuer]] <<input_cluster_issuer,cluster_issuer>>

Description: SSL certificate issuer to use. Usually you would configure this value as `letsencrypt-staging` or `letsencrypt-prod` on your root `*.tf` files.

Type: `string`

Default: `"ca-issuer"`

==== [[input_namespace]] <<input_namespace,namespace>>

Description: Namespace where the applications's Kubernetes resources should be created. Namespace will be created in case it doesn't exist.

Type: `string`

Default: `"velero"`

==== [[input_helm_values]] <<input_helm_values,helm_values>>

Description: Helm chart value overrides. They should be passed as a list of HCL structures.

Type: `any`

Default: `[]`

==== [[input_app_autosync]] <<input_app_autosync,app_autosync>>

Description: Automated sync options for the Argo CD Application resource.

Type:
[source,hcl]
----
object({
    allow_empty = optional(bool)
    prune       = optional(bool)
    self_heal   = optional(bool)
  })
----

Default:
[source,json]
----
{
  "allow_empty": false,
  "prune": true,
  "self_heal": true
}
----

==== [[input_dependency_ids]] <<input_dependency_ids,dependency_ids>>

Description: IDs of the other modules on which this module depends on.

Type: `map(string)`

Default: `{}`

==== [[input_backup_schedules]] <<input_backup_schedules,backup_schedules>>

Description: TBD

Type:
[source,hcl]
----
map(object({
    disabled    = optional(bool, false)
    labels      = optional(map(string), {})
    annotations = optional(map(string), {})
    schedule    = string
    template = object({
      # labels             = optional(map(string), {}) # TODO: test
      # annotations        = optional(map(string), {}) # TODO: test
      storageLocation    = optional(string)
      ttl                = optional(string)
      includedNamespaces = list(string)
      includedResources  = list(string)
      # enableSnapshot     = optional(bool, true)
    })
  }))
----

Default: `null`

==== [[input_enable_monitoring_dashboard]] <<input_enable_monitoring_dashboard,enable_monitoring_dashboard>>

Description: Boolean to enable the provisioning of a Velero dashboard for Grafana.

Type: `bool`

Default: `true`

==== [[input_alert_partially_failed_ratio]] <<input_alert_partially_failed_ratio,alert_partially_failed_ratio>>

Description: Percentage of partially failed backups before triggering a Prometheus alert

Type: `number`

Default: `0.25`

==== [[input_alert_failed_ratio]] <<input_alert_failed_ratio,alert_failed_ratio>>

Description: Percentage of failed backups before triggering a Prometheus alert

Type: `number`

Default: `0.25`

==== [[input_alert_backup_timeout]] <<input_alert_backup_timeout,alert_backup_timeout>>

Description: Timeout in seconds before triggering the last successful backup alert

Type: `number`

Default: `86400`
// END_TF_DOCS

=== Reference in table format

.Show tables
[%collapsible]
====
// BEGIN_TF_TABLES
= Requirements

[cols="a,a",options="header,autowidth"]
|===
|Name |Version
|[[requirement_argocd]] <<requirement_argocd,argocd>> |>= 4
|[[requirement_kubernetes]] <<requirement_kubernetes,kubernetes>> |~> 2
|[[requirement_null]] <<requirement_null,null>> |>= 3
|[[requirement_utils]] <<requirement_utils,utils>> |>= 1
|===

= Providers

[cols="a,a",options="header,autowidth"]
|===
|Name |Version
|[[provider_aws]] <<provider_aws,aws>> |n/a
|===

= Modules

[cols="a,a,a",options="header,autowidth"]
|===
|Name |Source |Version
|[[module_backup]] <<module_backup,backup>> |../ |
|===

= Resources

[cols="a,a",options="header,autowidth"]
|===
|Name |Type
|https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/region[aws_region.current] |data source
|===

= Inputs

[cols="a,a,a,a,a",options="header,autowidth"]
|===
|Name |Description |Type |Default |Required
|[[input_default_backup_storage]] <<input_default_backup_storage,default_backup_storage>>
|AWS S3 bucket configuration values for the bucket where the backups will be stored.
|

[source]
----
object({
    bucket_id    = string
    region       = string
    iam_role_arn = string
  })
----

|n/a
|yes

|[[input_cluster_name]] <<input_cluster_name,cluster_name>>
|Name given to the cluster. Value used for naming some the resources created by the module.
|`string`
|n/a
|yes

|[[input_base_domain]] <<input_base_domain,base_domain>>
|Base domain of the cluster. Value used for the ingress' URL of the application.
|`string`
|n/a
|yes

|[[input_argocd_namespace]] <<input_argocd_namespace,argocd_namespace>>
|Namespace used by Argo CD where the Application and AppProject resources should be created.
|`string`
|`"argocd"`
|no

|[[input_target_revision]] <<input_target_revision,target_revision>>
|Override of target revision of the application chart.
|`string`
|`"v1.0.0"`
|no

|[[input_cluster_issuer]] <<input_cluster_issuer,cluster_issuer>>
|SSL certificate issuer to use. Usually you would configure this value as `letsencrypt-staging` or `letsencrypt-prod` on your root `*.tf` files.
|`string`
|`"ca-issuer"`
|no

|[[input_namespace]] <<input_namespace,namespace>>
|Namespace where the applications's Kubernetes resources should be created. Namespace will be created in case it doesn't exist.
|`string`
|`"velero"`
|no

|[[input_helm_values]] <<input_helm_values,helm_values>>
|Helm chart value overrides. They should be passed as a list of HCL structures.
|`any`
|`[]`
|no

|[[input_app_autosync]] <<input_app_autosync,app_autosync>>
|Automated sync options for the Argo CD Application resource.
|

[source]
----
object({
    allow_empty = optional(bool)
    prune       = optional(bool)
    self_heal   = optional(bool)
  })
----

|

[source]
----
{
  "allow_empty": false,
  "prune": true,
  "self_heal": true
}
----

|no

|[[input_dependency_ids]] <<input_dependency_ids,dependency_ids>>
|IDs of the other modules on which this module depends on.
|`map(string)`
|`{}`
|no

|[[input_backup_schedules]] <<input_backup_schedules,backup_schedules>>
|TBD
|

[source]
----
map(object({
    disabled    = optional(bool, false)
    labels      = optional(map(string), {})
    annotations = optional(map(string), {})
    schedule    = string
    template = object({
      # labels             = optional(map(string), {}) # TODO: test
      # annotations        = optional(map(string), {}) # TODO: test
      storageLocation    = optional(string)
      ttl                = optional(string)
      includedNamespaces = list(string)
      includedResources  = list(string)
      # enableSnapshot     = optional(bool, true)
    })
  }))
----

|`null`
|no

|[[input_enable_monitoring_dashboard]] <<input_enable_monitoring_dashboard,enable_monitoring_dashboard>>
|Boolean to enable the provisioning of a Velero dashboard for Grafana.
|`bool`
|`true`
|no

|[[input_alert_partially_failed_ratio]] <<input_alert_partially_failed_ratio,alert_partially_failed_ratio>>
|Percentage of partially failed backups before triggering a Prometheus alert
|`number`
|`0.25`
|no

|[[input_alert_failed_ratio]] <<input_alert_failed_ratio,alert_failed_ratio>>
|Percentage of failed backups before triggering a Prometheus alert
|`number`
|`0.25`
|no

|[[input_alert_backup_timeout]] <<input_alert_backup_timeout,alert_backup_timeout>>
|Timeout in seconds before triggering the last successful backup alert
|`number`
|`86400`
|no

|===
// END_TF_TABLES
====
